### ISSUE TITLE
Can´t seem to compile correctly

### ISSUE THREAD

**Issue by alvarodecastro74** [davidkiss/storm-twitter-word-count#2]
I downloaded the project, compiled it with "mvn package", but it only produces a 12K jar file. Trying to run it with "storm jar storm-twitter-word-count-0.1.jar Topology" leads to "Could not find main class Topology"

**Comment by davidkiss** [comment]
I updated the pom.xml t create a fat jar that can be run with storm jar storm-twitter-word-count-jar-with-dependencies.jar com.kaviddiss.storm.Topology. Let me know if you still get the same error, otherwise let's close this ticket.

**Comment by alvarodecastro74** [comment]
Ok, did what you said using a twitter4j.properties file as described at http://twitter4j.org/en/configuration.html#systempropertyconfiguration and it seems to work. Thanks!
